### ISSUE TITLE
filter npm scripts to only list those in selected folders?

### ISSUE THREAD

**Issue by ckot** [folke/vscode-monorepo-workspace#44]
Hi,

I'm noticing that the npm scripts for **all** of my yarn workspaces are listed, not merely the ones associated with the folders I've configured this to display.

Am I doing something wrong, is this a feature request, or is this a limitation in vscode itself, such as https://github.com/microsoft/vscode/issues/71635  ?

**Comment by ckot** [comment]
NVM.  I just de-selected the project root folder and discovered that the npm scripts for all of the non-selected yarn workspaces go away

I'd close this, but I thought perhaps you should see it first.  Perhaps this should be documented, as at least *one* person didn't find this obvious :)

**Comment by folke** [comment]
Glad you sorted it out. Thanks!
