### ISSUE TITLE
[FR] More emoji via `monorepoWorkspace.moreFolders: [{prefix, regex}]`?

### ISSUE THREAD

**Issue by mikestopcontinues** [folke/vscode-monorepo-workspace#45]
Hey, I've found I could use a bit more differentiation between package types in my workspace. There's definitely value to being able to manage settings through the settings UI, but for cases where more emoji would be useful, how about an array config? E.G. `monorepoWorkspace.moreFolders: [{prefix, regex}]`

While I was looking around the code, I also found what I think might be [a typo](https://github.com/folke/vscode-monorepo-workspace/blob/master/src/extension.ts#L33). Should it be `"prefix.unkown"`?

Thanks!

**Comment by folke** [comment]
That's a great idea! I'll see if I can add this in the coming days.

Definitely a typo. Will fix that as well :)

**Comment by mikestopcontinues** [comment]
Cool, man! Thanks!

**Comment by folke** [comment]
Just released v1.2.0 with this feature! It can take a couple of minutes before the latest version is deployed on the marketplace

**Comment by mikestopcontinues** [comment]
Hey, I just got the update. Thanks a million!
