### ISSUE TITLE
Packages don't work on Windows

### ISSUE THREAD

**Issue by ryuuji3** [folke/vscode-monorepo-workspace#47]
Hi,

I really like this extension except that it appears not to work on windows; the paths to packages are not correct for Windows.

It appears that the path to my package is created as "/Users/Josh/Projects/<project>" but that doesn't resolve correctly; it should instead of "C:/Users/Josh/Projects/<project>".

Thank you!

**Comment by folke** [comment]
Thank you for reporting this. I'll fix this asap.

**Comment by folke** [comment]
Just released 1.1.3 containing the fix.

might take a few minutes for it to show up on the marketplace

**Comment by ryuuji3** [comment]
Thank you so much you're the best! Ive never done vscode extensions so I
didn't know where to start.
