### ISSUE TITLE
Make includeRoot configurable from VSCode settings

### ISSUE THREAD

**Issue by ghaiklor-wix** [folke/vscode-monorepo-workspace#56]
Hi! Thanks for a great work. I never wrote VSCode extensions, so I don't know how exactly it could be done, but can we made this field configurable?

https://github.com/folke/vscode-monorepo-workspace/blob/master/src/extension.ts#L51

Right now, when I'm sync my Rush projects with workspace folders, it includes the root as well. I want to get rid of root in workspace because it makes a conflict with types then.

**Comment by folke** [comment]
I just released a new version, including this option. Thank you for the suggestion!
