### ISSUE TITLE
helpwanted: subdirectories not recognised

### ISSUE THREAD

**Issue by TGTGamer** [folke/vscode-monorepo-workspace#58]
Heya, so I'm running a mono repository with the following stack, however, whenever I try to use your extension it won't see any of my packages. I'm not very good with regex so that might be the issue (reset it to standard now). 

```
root: smartcloud-dev
./package.json
./packages/public/components/package.json
./packages/public/webfront/package.json
./packages/public/webpanel/package.json
./packages/containers/discord/package.json
```

![image](https://user-images.githubusercontent.com/11413796/89107118-b0e70f80-d426-11ea-9e9a-f3f0431fccf5.png)

**Comment by folke** [comment]
Those settings are for the icons only.

You need to configure your monorepo using one of npm7, yarn, lerna, pnpm, ...

The easiest in your case, would be to edit the package.json file in your top-level directory and add a workspace key as in:

``json
{
"workspaces": [
    "packages/**/*",
  ],
}
```
